# Ansible Inventory - Generated by Terraform
# Kubernetes Cluster Configuration

[k8s_lb]
${lb.vm_name} ansible_host=${lb.vm_ip} ansible_user=ubuntu ansible_ssh_private_key_file=${ssh_key}

[k8s_masters]
%{ for idx, master in masters ~}
${master.vm_name} ansible_host=${master.vm_ip} ansible_user=ubuntu ansible_ssh_private_key_file=${ssh_key} k8s_role=master node_name=${master.vm_name}
%{ endfor ~}

[k8s_first_master]
${masters[0].vm_name} ansible_host=${masters[0].vm_ip} ansible_user=ubuntu ansible_ssh_private_key_file=${ssh_key}

[k8s_additional_masters]
%{ for idx, master in masters ~}
%{ if idx > 0 ~}
${master.vm_name} ansible_host=${master.vm_ip} ansible_user=ubuntu ansible_ssh_private_key_file=${ssh_key}
%{ endif ~}
%{ endfor ~}

[k8s_workers]
%{ for worker in workers ~}
${worker.vm_name} ansible_host=${worker.vm_ip} ansible_user=ubuntu ansible_ssh_private_key_file=${ssh_key} k8s_role=worker node_name=${worker.vm_name}
%{ endfor ~}

%{ if length(storage) > 0 ~}
[storage]
${storage[0].vm_name} ansible_host=${storage[0].vm_ip} ansible_user=ubuntu ansible_ssh_private_key_file=${ssh_key}
%{ endif ~}

[k8s_cluster:children]
k8s_masters
k8s_workers

[all:children]
k8s_lb
k8s_cluster
%{ if length(storage) > 0 ~}
storage
%{ endif ~}

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'