# Generated Ansible Inventory for HomeLab
# Generated by Terraform

[k8s_masters]
%{ for name, config in masters ~}
${name} ansible_host=${config.ip_address} ansible_user=ubuntu
%{ endfor ~}

[k8s_workers]
%{ for name, config in workers ~}
${name} ansible_host=${config.ip_address} ansible_user=ubuntu worker_type=${contains(split(",", config.tags), "storage") ? "storage" : "compute"}
%{ endfor ~}

[haproxy]
%{ for lb in haproxy ~}
${lb.name} ansible_host=${lb.ip} ansible_user=ubuntu
%{ endfor ~}

[infrastructure]
%{ if storage_ip != null ~}
storage-server ansible_host=${storage_ip} ansible_user=ubuntu
%{ endif ~}
gitlab-server ansible_host=${gitlab_ip} ansible_user=ubuntu
monitoring-server ansible_host=${monitoring_ip} ansible_user=ubuntu
database-server ansible_host=${database_ip} ansible_user=ubuntu

[k8s_cluster:children]
k8s_masters
k8s_workers

[all:vars]
ansible_ssh_private_key_file=~/.ssh/homelab_rsa
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3

# Kubernetes Configuration
k8s_version=1.29.0
k8s_pod_subnet=10.244.0.0/16
k8s_service_subnet=10.96.0.0/12
k8s_api_vip=10.1.1.9

# Network Configuration
cluster_domain=cluster.local
cluster_dns=10.96.0.10
