loki:
  enabled: true
  persistence:
    enabled: true
    size: 10Gi
  
promtail:
  enabled: true
  
grafana:
  enabled: false  # Already deployed with prometheus stack
  
# Loki configuration
loki-stack:
  loki:
    config:
      chunk_store_config:
        max_look_back_period: 720h  # 30 days
      table_manager:
        retention_deletes_enabled: true
        retention_period: 720h
