---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snmp-exporter
  namespace: monitoring
  labels:
    app: snmp-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snmp-exporter
  template:
    metadata:
      labels:
        app: snmp-exporter
    spec:
      containers:
      - name: snmp-exporter
        image: prom/snmp-exporter:v0.29.0
        ports:
        - containerPort: 9116
          name: http

---
apiVersion: v1
kind: Service
metadata:
  name: snmp-exporter
  namespace: monitoring
  labels:
    app: snmp-exporter
spec:
  ports:
  - port: 9116
    targetPort: 9116
    name: http
  selector:
    app: snmp-exporter

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-snmp-config
  namespace: monitoring
data:
  snmp-scrape-config.yaml: |
    - job_name: 'mikrotik-router'
      static_configs:
        - targets:
          - 10.0.0.1  # Mikrotik router IP
      metrics_path: /snmp
      params:
        module: [if_mib]  # Use built-in if_mib module
        auth: [public_v2]
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: snmp-exporter.monitoring:9116

---
# ServiceMonitor for automatic Prometheus discovery
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: snmp-exporter
  namespace: monitoring
  labels:
    app: snmp-exporter
spec:
  selector:
    matchLabels:
      app: snmp-exporter
  endpoints:
  - port: http
    interval: 30s
