apiVersion: v1
kind: Secret
metadata:
  name: additional-scrape-configs
  namespace: monitoring
stringData:
  prometheus-additional.yaml: |
    - job_name: 'mikrotik-router'
      static_configs:
        - targets:
          - 10.0.0.1  # Mikrotik router IP
      metrics_path: /snmp
      params:
        module: [if_mib]
        auth: [public_v2]
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: snmp-exporter.monitoring.svc.cluster.local:9116
