---
# Immich PostgreSQL Database
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-postgres-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: Secret
metadata:
  name: immich-postgres-secret
  namespace: media
type: Opaque
stringData:
  POSTGRES_USER: immich
  POSTGRES_PASSWORD: immich_secure_password_change_me
  POSTGRES_DB: immich

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-postgres
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-postgres
  template:
    metadata:
      labels:
        app: immich-postgres
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: postgres
          image: tensorchord/pgvecto-rs:pg14-v0.2.0
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: immich-postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: immich-postgres-secret
                  key: POSTGRES_DB
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: immich-postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: immich-postgres
  namespace: media
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: immich-postgres
