# Variables specific to Kubernetes master nodes
k8s_node_role: master

# Control plane configuration
api_server_bind_port: 6443
etcd_listen_port: 2379
etcd_peer_port: 2380

# API Server configuration
api_server_cert_sans:
  - "{{ control_plane_endpoint }}"
  - "kubernetes"
  - "kubernetes.default"
  - "kubernetes.default.svc"
  - "kubernetes.default.svc.{{ k8s_dns_domain }}"
  - "localhost"
  - "127.0.0.1"

# etcd configuration
etcd_data_dir: /var/lib/etcd
etcd_wal_dir: /var/lib/etcd/wal
etcd_snapshot_count: 10000
etcd_heartbeat_interval: 100
etcd_election_timeout: 1000

# Scheduler configuration
scheduler_bind_address: "0.0.0.0"
scheduler_port: 10259

# Controller Manager configuration
controller_manager_bind_address: "0.0.0.0"
controller_manager_port: 10257

# Kubelet configuration for masters
kubelet_config:
  maxPods: "{{ max_pods_per_node }}"
  clusterDNS: ["{{ k8s_service_subnet | ansible.utils.nthhost(10) }}"]
  clusterDomain: "{{ k8s_dns_domain }}"
  cgroupDriver: "systemd"
  failSwapOn: false
  serverTLSBootstrap: true

# Master node taints
master_node_taints:
  - key: "node-role.kubernetes.io/control-plane"
    effect: "NoSchedule"

# Feature gates (if needed)
feature_gates: {}

# Audit policy (if enabled)
audit_policy_path: /etc/kubernetes/audit-policy.yaml
audit_log_path: /var/log/kubernetes/audit.log
audit_log_maxage: 30
audit_log_maxbackup: 10
audit_log_maxsize: 100