apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: media
  labels:
    app: plex
    tier: media-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
        tier: media-server
    spec:
      nodeSelector:
        nvidia.com/gpu.present: "true"
      containers:
      - name: plex
        image: linuxserver/plex:latest
        ports:
        - containerPort: 32400
          name: plex-web
        - containerPort: 1900
          name: dlna-udp
          protocol: UDP
        - containerPort: 5353
          name: discovery-udp
          protocol: UDP
        - containerPort: 8324
          name: roku-control
        - containerPort: 32410
          name: gdm-32410
          protocol: UDP
        - containerPort: 32412
          name: gdm-32412
          protocol: UDP
        - containerPort: 32413
          name: gdm-32413
          protocol: UDP
        - containerPort: 32414
          name: gdm-32414
          protocol: UDP
        - containerPort: 32469
          name: dlna-tcp
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: VERSION
          value: "docker"
        - name: TZ
          value: "America/New_York"
        - name: NVIDIA_VISIBLE_DEVICES
          value: "all"
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "compute,video,utility"
        volumeMounts:
        - name: config
          mountPath: /config
        - name: media
          mountPath: /media
        - name: transcode
          mountPath: /transcode
        resources:
          requests:
            cpu: "2"
            memory: "4Gi"
          limits:
            cpu: "8"
            memory: "16Gi"
            nvidia.com/gpu: 1
        securityContext:
          privileged: true
        livenessProbe:
          httpGet:
            path: /web/index.html
            port: 32400
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /web/index.html
            port: 32400
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: plex-config-pvc
      - name: media
        persistentVolumeClaim:
          claimName: plex-media-pvc
      - name: transcode
        emptyDir:
          sizeLimit: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: media
  labels:
    app: plex
spec:
  type: LoadBalancer
  loadBalancerIP: 10.1.1.102
  selector:
    app: plex
  ports:
  - name: plex-web
    port: 32400
    targetPort: 32400
  - name: dlna-udp
    port: 1900
    targetPort: 1900
    protocol: UDP
  - name: discovery-udp
    port: 5353
    targetPort: 5353
    protocol: UDP
---
apiVersion: v1
kind: Namespace
metadata:
  name: media
  labels:
    name: media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-ssd
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Gi
