---
- name: Setup Kubernetes Prerequisites
  hosts: k8s_cluster
  become: yes
  vars:
    kubernetes_version: "1.31.0"
    containerd_version: "1.7.22"
    
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gpg
          - software-properties-common
        state: present
        
    - name: Disable swap
      shell: |
        swapoff -a
        sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
        
    - name: Enable kernel modules
      shell: |
        cat <<EOF | tee /etc/modules-load.d/k8s.conf
        overlay
        br_netfilter
        EOF
        modprobe overlay
        modprobe br_netfilter
        
    - name: Set kernel parameters
      shell: |
        cat <<EOF | tee /etc/sysctl.d/k8s.conf
        net.bridge.bridge-nf-call-iptables  = 1
        net.bridge.bridge-nf-call-ip6tables = 1
        net.ipv4.ip_forward                 = 1
        EOF
        sysctl --system
        
    - name: Install containerd
      shell: |
        # Install containerd
        apt-get update
        apt-get install -y containerd
        
        # Configure containerd
        mkdir -p /etc/containerd
        containerd config default | tee /etc/containerd/config.toml
        
        # Enable SystemdCgroup
        sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
        
        # Restart containerd
        systemctl restart containerd
        systemctl enable containerd
        
    - name: Add Kubernetes apt repository
      shell: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list
        apt-get update
        
    - name: Install Kubernetes components
      apt:
        name:
          - kubelet=1.31.0-1.1
          - kubeadm=1.31.0-1.1
          - kubectl=1.31.0-1.1
        state: present
        
    - name: Hold Kubernetes packages
      shell: |
        apt-mark hold kubelet kubeadm kubectl
        
    - name: Enable kubelet
      systemd:
        name: kubelet
        enabled: yes
        state: started