---
- name: Initialize first control plane
  hosts: first_master,additional_masters
  become: yes
  tasks:
    - name: Install Calico network plugin
      shell: |
        kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.29.2/manifests/tigera-operator.yaml
        kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.29.2/manifests/custom-resources.yaml
