---
- name: Setup Containerd
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist
      become: yes

    - name: Install containerd
      apt:
        name: containerd
        state: present
        update_cache: yes

    - name: create /etc/containerd directory
      file:
        path: /etc/containerd
        state: directory
        mode: '0755'

    - name: Generate default containerd configuration
      command: containerd config default
      register: containerd_config

    - name: Save containerd configuration to file
      copy:
        content: "{{ containerd_config.stdout }}"
        dest: /etc/containerd/config.toml

    - name: Ensure SystemdCgroup is set to true
      lineinfile:
        path: /etc/containerd/config.toml
        regexp: "            SystemdCgroup = false"
        line: "            SystemdCgroup = true"
      notify: Restart containerd

  handlers:
    - name: Restart containerd
      service:
        name: containerd
        state: restarted


