---
- name: Join additional control plane nodes
  hosts: additional_masters
  become: yes
  gather_facts: yes
  tasks:
    - name: Check if this node is already joined (kubelet config exists)
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_conf

    - name: Join the cluster as a control plane node
      command: "{{ hostvars[groups['first_master'][0]].join_command_master }}"
      when: not kubelet_conf.stat.exists
