---
- name: Provision Kubernetes Cluster using Kubeadm
  hosts: all
  become: yes
  vars:
    k8s_version: "1.32"
    pod_network_cidr: "192.168.0.0/16"

  tasks:
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gpg
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add Kubernetes apt key
      block:
        - name: Ensure /etc/apt/keyrings directory exists
          file:
            path: /etc/apt/keyrings
            state: directory
            mode: '0755'

        - name: Download Kubernetes apt key
          get_url:
            url: "https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key"
            dest: "/tmp/Release.key"
            mode: '0644'
            timeout: 30

        - name: Convert Kubernetes apt key to GPG format
          command: gpg --batch --yes --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/Release.key

    - name: add k8s repo
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /"
        state: present
        update_cache: yes

    - name: Install kubeadm, kubelet, kubectl
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes

    - name: Hold kubeadm, kubelet, kubectl at current version
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl

