# Ansible Inventory - Auto-generated by Terraform

[k8s_masters]
%{ for name, config in masters ~}
${config.ip} hostname=${config.hostname}
%{ endfor ~}

[etcd]
%{ for name, config in etcd_nodes ~}
${config.ip} hostname=${config.hostname}
%{ endfor ~}

[k8s_workers]
%{ for name, config in workers ~}
${config.ip} hostname=${config.hostname}
%{ endfor ~}

[infrastructure]
%{ for name, config in infrastructure ~}
${config.ip} hostname=${config.hostname}
%{ endfor ~}

[k8s_cluster:children]
k8s_masters
k8s_workers

[all:vars]
ansible_user=ubuntu
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_become=yes